steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Test
# OK YOU KNOW WHAT? IF TESTS DON'T WORK IN CI, I JUST WON'T DO TESTS. :(
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']